# Generated by Django 5.1.1 on 2024-10-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                error_messages={"required": "Role to be provided"}, max_length=12
            ),
        ),
    ]
