# Generated by Django 5.1.2 on 2024-10-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
            },
        ),
        migrations.AlterField(
            model_name="job",
            name="type",
            field=models.IntegerField(
                choices=[(1, "Full time"), (2, "Part time"), (3, "Internship")]
            ),
        ),
    ]
